name: Build theducxinhsrt exe (Windows)

on:
  push:
    branches: [ "main", "master" ]
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller
          if exist requirements.txt pip install -r requirements.txt

      - name: Build with PyInstaller
        run: |
          pyinstaller --noconfirm --onefile --name theducxinhsrt main.py

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: theducxinhsrt-exe
          path: dist/theducxinhsrt.exe
