name: Build theducxinhSRT exe (Windows)

on:
  push:
    branches:
      - main

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyinstaller

      - name: Build executable
        run: |
          pyinstaller main.py --onefile --noconfirm ^
            --name theducxinhSRT ^
            --hidden-import PySimpleGUI ^
            --hidden-import google.generativeai ^
            --hidden-import google ^
            --collect-all PySimpleGUI ^
            --collect-all google ^
            --collect-all google.generativeai
        shell: cmd

      - name: Test executable
        run: |
          echo Testing EXE...
          dist\theducxinhSRT.exe || exit 1
        shell: cmd

      - name: Zip build folder
        run: powershell Compress-Archive -Path dist\theducxinhSRT.exe -DestinationPath theducxinhSRT.zip

      - name: Upload zip
        uses: actions/upload-artifact@v4
        with:
          name: theducxinhSRT-zip
          path: theducxinhSRT.zip
