name: Build theducxinhSRT exe (Windows)

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
    - name: Checkout source code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install PySimpleGUI pyinstaller

    - name: Build executable
      run: |
        pyinstaller --onefile --noconsole --hidden-import PySimpleGUI main.py

    - name: Test executable
      run: |
        echo "Testing EXE..."
        dist\main.exe || exit 1

    - name: Zip build folder
      run: |
        powershell Compress-Archive -Path dist\* -DestinationPath build.zip

    - name: Upload zip
      uses: actions/upload-artifact@v4
      with:
        name: theducxinhSRT-exe
        path: build.zip
