name: build-windows

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
    - name: Checkout source code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pyinstaller

    - name: Build executable
      run: pyinstaller --onefile main.py

    - name: Test executable
      run: |
        echo Running the built EXE...
        dist\main.exe || exit 1

    - name: Zip build folder
      run: powershell Compress-Archive -Path dist\* -DestinationPath build.zip

    - name: Upload zip
      uses: actions/upload-artifact@v4
      with:
        name: windows-build
        path: build.zip
